default['sickbeard']['location']   = "/opt/sickbeard"
default['sickbeard']['user']   = "sickbeard"
default['sickbeard']['group']   = "sickbeard"
default['sickbeard']['data_dir']   = "~/.sickbeard"
default['sickbeard']['nzb_method'] = "sabnzbd"
default['sickbeard']['sab_username'] = ""
default['sickbeard']['sab_password'] = ""
default['sickbeard']['sab_apikey'] = ""
default['sickbeard']['sab_category'] = "tv"
default['sickbeard']['sab_host'] = "http://localhost:8000/"
default['sickbeard']['provider_order'] = "nzbs_r_us nzbs_org womble_s_index tvtorrents ezrss btn sick_beard_index"
default['sickbeard']['newznab_data'] = "Sick Beard Index|http://lolo.sickbeard.com/||0!!!NZBs.org|http://beta.n zbs.org/||0"

